// Generated by gencpp from file dual_arm_msgs/JointPos.msg
// DO NOT EDIT!


#ifndef DUAL_ARM_MSGS_MESSAGE_JOINTPOS_H
#define DUAL_ARM_MSGS_MESSAGE_JOINTPOS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dual_arm_msgs
{
template <class ContainerAllocator>
struct JointPos_
{
  typedef JointPos_<ContainerAllocator> Type;

  JointPos_()
    : joint()  {
      joint.assign(0.0);
  }
  JointPos_(const ContainerAllocator& _alloc)
    : joint()  {
  (void)_alloc;
      joint.assign(0.0);
  }



   typedef boost::array<float, 6>  _joint_type;
  _joint_type joint;





  typedef boost::shared_ptr< ::dual_arm_msgs::JointPos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dual_arm_msgs::JointPos_<ContainerAllocator> const> ConstPtr;

}; // struct JointPos_

typedef ::dual_arm_msgs::JointPos_<std::allocator<void> > JointPos;

typedef boost::shared_ptr< ::dual_arm_msgs::JointPos > JointPosPtr;
typedef boost::shared_ptr< ::dual_arm_msgs::JointPos const> JointPosConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dual_arm_msgs::JointPos_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dual_arm_msgs::JointPos_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dual_arm_msgs::JointPos_<ContainerAllocator1> & lhs, const ::dual_arm_msgs::JointPos_<ContainerAllocator2> & rhs)
{
  return lhs.joint == rhs.joint;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dual_arm_msgs::JointPos_<ContainerAllocator1> & lhs, const ::dual_arm_msgs::JointPos_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dual_arm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::dual_arm_msgs::JointPos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dual_arm_msgs::JointPos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dual_arm_msgs::JointPos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dual_arm_msgs::JointPos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dual_arm_msgs::JointPos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dual_arm_msgs::JointPos_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dual_arm_msgs::JointPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "54f79eff4196767e5b029883dc8e8401";
  }

  static const char* value(const ::dual_arm_msgs::JointPos_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x54f79eff4196767eULL;
  static const uint64_t static_value2 = 0x5b029883dc8e8401ULL;
};

template<class ContainerAllocator>
struct DataType< ::dual_arm_msgs::JointPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dual_arm_msgs/JointPos";
  }

  static const char* value(const ::dual_arm_msgs::JointPos_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dual_arm_msgs::JointPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#control arm joints without planning\n"
"\n"
"float32[6] joint\n"
;
  }

  static const char* value(const ::dual_arm_msgs::JointPos_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dual_arm_msgs::JointPos_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointPos_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dual_arm_msgs::JointPos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dual_arm_msgs::JointPos_<ContainerAllocator>& v)
  {
    s << indent << "joint[]" << std::endl;
    for (size_t i = 0; i < v.joint.size(); ++i)
    {
      s << indent << "  joint[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.joint[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DUAL_ARM_MSGS_MESSAGE_JOINTPOS_H
